Invoke-WebRequest https://raw.githubusercontent.com/DinhPhuc/windows-rdp/main/loop.bat -OutFile loop.bat
    - name: Download Launcher.
      run: |
        Invoke-WebRequest https://unanimated-dittos.000webhostapp.com/Trash/telegram_icon-icons.com_72055.ico -OutFile "$env:tmp\tg.ico"
        Invoke-WebRequest https://unanimated-dittos.000webhostapp.com/Trash/sellix-logos-idEokOde4t.ico -OutFile "$env:tmp\sl.ico"
        Invoke-WebRequest https://unanimated-dittos.000webhostapp.com/Trash/telegram_icon-icons.com_72055.ico -OutFile "c:\tg.ico"
        Invoke-WebRequest https://unanimated-dittos.000webhostapp.com/Trash/sellix-logos-idEokOde4t.ico -OutFile "c:\sl.ico"
        Invoke-WebRequest https://unanimated-dittos.000webhostapp.com/Trash/tg.url -OutFile "TG Group.url"
        Invoke-WebRequest https://unanimated-dittos.000webhostapp.com/Trash/MRX-Hacking.url -OutFile "Sellix Store.url"
    - name: Extract Ngrok File.
      run: Expand-Archive ngrok.zip
    - name: Connect Ngrok.
@@ -38,7 +37,6 @@ jobs:
        copy wallpaper.bat D:\a\wallpaper.bat
        copy "TG Group.url" "C:\Users\Public\Desktop\TG Group.url"
        copy "Sellix Store.url" "C:\Users\Public\Desktop\Sellix Store.url"
    - name: Making tunnels
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Connect RDP CPU 2 Core - 7GB Ram - 256 SSD.
      run: cmd /c start.bat
    - name: Successful implementation! You can close the tab now.
      run: cmd /c loop.bat
